name: Go CI

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
  push:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.9'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Install libknot dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libknot-dev

    - name: Get dependencies
      run: |
        go mod download
        go mod verify
        go mod tidy

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Vet
      run: make vet

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=5m

    - name: Install security dependencies
      run: |
        sudo apt-get install -y jq
        go install github.com/securego/gosec/v2/cmd/gosec@latest

    - name: Security
      run: make security
