name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-amd64:
    uses: ./.github/workflows/release-common.yml
    with:
      runner: ubuntu-latest
      arch: amd64

  build-arm64:
    uses: ./.github/workflows/release-common.yml
    with:
      runner: ubuntu-24.04-arm
      arch: arm64

  create-release:
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist-artifacts

      - name: Prepare release files
        run: |
          mkdir -p release
          find dist-artifacts -name "*.tar.gz" -exec cp {} release/ \;
          find dist-artifacts -name "*.sha256" -exec cp {} release/ \;

          # Create consolidated checksums file
          cd release
          cat *.sha256 > checksums.txt
          ls -lh

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
