name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libknot-dev pkg-config

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          install-only: true

      - name: Run GoReleaser for amd64
        run: |
          goreleaser build --single-target --snapshot --clean
        env:
          GOARCH: amd64
          GOOS: linux

      - name: Create archive
        run: |
          cd dist/knot-exporter_linux_amd64_v1
          tar czf ../knot-exporter_linux_amd64.tar.gz knot-exporter ../../README.md
          cd ..
          sha256sum knot-exporter_linux_amd64.tar.gz > knot-exporter_linux_amd64.tar.gz.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: knot-exporter-amd64
          path: |
            dist/knot-exporter_linux_amd64.tar.gz
            dist/knot-exporter_linux_amd64.tar.gz.sha256

  build-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libknot-dev pkg-config

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          install-only: true

      - name: Run GoReleaser for arm64
        run: |
          goreleaser build --single-target --snapshot --clean
        env:
          GOARCH: arm64
          GOOS: linux

      - name: Create archive
        run: |
          cd dist/knot-exporter_linux_arm64_v8.0
          tar czf ../knot-exporter_linux_arm64.tar.gz knot-exporter ../../README.md
          cd ..
          sha256sum knot-exporter_linux_arm64.tar.gz > knot-exporter_linux_arm64.tar.gz.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: knot-exporter-arm64
          path: |
            dist/knot-exporter_linux_arm64.tar.gz
            dist/knot-exporter_linux_arm64.tar.gz.sha256

  create-release:
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist-artifacts

      - name: Prepare release files
        run: |
          mkdir -p release
          find dist-artifacts -name "*.tar.gz" -exec cp {} release/ \;
          find dist-artifacts -name "*.sha256" -exec cp {} release/ \;

          # Create consolidated checksums file
          cd release
          cat *.sha256 > checksums.txt
          ls -lh

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}